# Generated by Django 4.0.4 on 2022-08-25 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('is_anonymous', models.BooleanField(choices=[(True, 'Анонимный'), (False, 'Публичный')], default=False, verbose_name='Анонимный или публоичный')),
                ('type', models.CharField(choices=[('quiz', 'Викторина'), ('regular', 'Опрос')], max_length=150, verbose_name='Тип вопроса')),
                ('explanation', models.TextField(verbose_name='Подсказка после завершения теста')),
                ('open_period', models.IntegerField(default=0, help_text='0 если не имеет ограничения во времени', verbose_name='Время завершения теста')),
                ('img', models.FileField(blank=True, null=True, upload_to='File/Image/', verbose_name='Фотография')),
                ('video_gif', models.FileField(blank=True, null=True, upload_to='File/Video_Gif/', verbose_name='Видео или Гиф')),
            ],
            options={
                'verbose_name': 'Вопрос сборнику',
                'verbose_name_plural': 'Вопросы сборников',
            },
        ),
        migrations.CreateModel(
            name='Poll_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Номер или название сборника')),
            ],
            options={
                'verbose_name': 'Сборник вопроса',
                'verbose_name_plural': 'Сборники вопросов',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True, unique=True)),
                ('username', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField()),
                ('true_option', models.IntegerField()),
                ('name', models.CharField(max_length=250, null=True)),
                ('poll_id', models.CharField(max_length=250, null=True)),
                ('answer', models.CharField(max_length=250, null=True)),
                ('point', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ответ Юзера',
                'verbose_name_plural': 'Ответы Юзеров',
            },
        ),
        migrations.CreateModel(
            name='Poll_answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.CharField(max_length=250, verbose_name='Вариант ответа')),
                ('correct_option', models.BooleanField(default=False, help_text='True - правильный\n\nFalse - неправильный', verbose_name='Тип ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest', to='main.poll')),
            ],
            options={
                'verbose_name': 'Вариант Ответа',
                'verbose_name_plural': 'Варианты Ответов',
            },
        ),
        migrations.AddField(
            model_name='poll',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nam', to='main.poll_class', verbose_name='Сборник'),
        ),
    ]
