# Generated by Django 4.0.4 on 2022-08-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll_type',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': '1 Предметы'},
        ),
        migrations.AlterField(
            model_name='poll',
            name='open_period',
            field=models.IntegerField(default=30, help_text='0 если не имеет ограничения во времени', verbose_name='Время завершения теста'),
        ),
        migrations.AlterField(
            model_name='poll_type',
            name='type',
            field=models.CharField(max_length=250, unique=True, verbose_name='Предмет'),
        ),
    ]
