# Generated by Django 4.0.4 on 2022-08-26 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='answer',
            field=models.TextField(default=1, verbose_name='Варианты ответа'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='open_period',
            field=models.IntegerField(default=10, help_text='0 если не имеет ограничения во времени', verbose_name='Время завершения теста'),
        ),
        migrations.AlterField(
            model_name='poll_answer',
            name='options',
            field=models.CharField(max_length=250, verbose_name='Вариант ответа (F1,F2)'),
        ),
        migrations.AlterField(
            model_name='poll_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest', to='main.poll', verbose_name='Вопрос'),
        ),
    ]
