# Generated by Django 4.0.4 on 2022-08-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_poll_answer_alter_poll_open_period_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name': 'Вопрос сборнику', 'verbose_name_plural': 'Вопросы сборников 2'},
        ),
        migrations.AlterModelOptions(
            name='poll_answer',
            options={'verbose_name': 'Вариант Ответа', 'verbose_name_plural': 'Варианты Ответов 3'},
        ),
        migrations.AlterModelOptions(
            name='poll_class',
            options={'verbose_name': 'Сборник вопроса', 'verbose_name_plural': 'Сборники вопросов 1'},
        ),
        migrations.AddField(
            model_name='user_answer',
            name='chat_id',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poll',
            name='type',
            field=models.CharField(choices=[('quiz', 'Викторина'), ('regular', 'Опрос')], default='Викторина', max_length=150, verbose_name='Тип вопроса'),
        ),
    ]
